version: "3"

services:

  redis-cluster:
    image: grokzen/redis-cluster
    restart: always
    ports:
      - '7000-7050:7000-7050'
      - '5000-5010:5000-5010'
    environment:
      IP: ${REDIS_CLUSTER_IP}
      SENTINEL: 'false'

  shortener_api:
    build: .
    restart: always
    volumes:
      - ./:/usr/app
    ports:
      - ${PORT}:3000
    environment:
      SERVER_NAME: ${SERVER_NAME}
      PORT: ${PORT}
      BASE_URL: ${BASE_URL}
      ## Edit redis real ip
      REDIS_CONTAINER_IP: 207.46.228.9

volumes:
  db_data:
    driver: local